@startuml
!include <C4/C4_Container>

title C4 Diagram - Контекст

Person(customer, "Пользователь", "Человек, использующий систему для управления отоплением и получения данных о температуре.")

System(monolith, "Монолитное приложение", "Приложение Java", "Получает данные о температуре через REST API и управляет системами отопления.")
System_Ext(api, "Внешний источник данных", "REST API", "Система отопления, установленная в каждом доме. Передает показания температуры и управляет отопителями.")
ContainerDb(database, "База данных", "PostgreSQL", "Хранит температурные данные и настройки управления отоплением.")

Rel(customer, monolith, "Взаимодействует через пользовательский интерфейс", "HTTP/HTTPS")
Rel(monolith, api, "Запрашивает данные о температуре", "REST API (JSON)")
Rel(monolith, api, "Передает команды управления отоплением", "REST API (JSON)")
Rel(monolith, database, "Сохраняет и извлекает данные", "SQL")

@enduml